backend:
  name: github
  repo: shahcoding/shahcoding.github.io
  branch: decap-test
  base_url: https://cms.shahcoding.workers.dev
  auth_endpoint: auth

# If your site is hosted at shahcoding.github.io,
# ensure these paths exist in your repo
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Notes", name: "notes", widget: "markdown" }